version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-justdoit}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-justdoit}
      - POSTGRES_DB=${DB_NAME:-justdoit}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 