services:
  - type: web
    name: justdoit
    env: node
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && npm install
    startCommand: cd server && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: justdoit-db
          property: connectionString

databases:
  - name: justdoit-db
    databaseName: justdoit
    user: justdoit
    plan: free