services:
  - type: web
    name: justdoit-server
    env: docker
    dockerfilePath: server/Dockerfile
    dockerCommand: node index.js
    envVars:
      - key: DB_HOST
        value: your-production-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: your-production-db-user
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: bet
      - key: USE_LOCAL_DB
        value: false
      - key: NODE_ENV
        value: production
      - key: RENDER_DB_URL
        sync: false
    healthCheckPath: /api
    autoDeploy: true
    plan: free
    region: singapore
    scaling:
      minInstances: 1
      maxInstances: 1
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"