services:
  - type: web
    name: justdoit-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8081
      - key: DATABASE_URL
        fromDatabase:
          name: justdoit-db
          property: internalConnectionString
      - key: DB_HOST
        fromDatabase:
          name: justdoit-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: justdoit-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: justdoit-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: justdoit-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: justdoit-db
          property: password
    autoDeploy: true
    branch: main
    healthCheckPath: /api
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"

databases:
  - name: justdoit-db
    databaseName: justdoit
    user: justdoit
    plan: free
    region: singapore 