services:
  - type: web
    name: justdoit-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8081
    autoDeploy: true
    branch: main
    healthCheckPath: /api
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"

databases:
  - name: justdoit-db
    databaseName: justdoit
    user: justdoit
    plan: free
    region: singapore 